import "../globals.css";

export const metadata = {
  title: "Badminton PH: Sign In",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="h-lvh w-lvw flex justify-center items-center">
        {children}
    </div>
  );
}
